#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: poolName
    type: string
    default: ADO-1ES-Pool

  - name: imageOverride
    type: string
    default: ADO-MMS22-SQL19

  - name: artifactName
    type: string
    default: Artifacts

  - name: prebuildSteps
    type: stepList
    default: []

jobs:
- job: build_nugets

  pool:
    name: ${{parameters.poolName }}
    demands:
    - imageOverride -equals ${{ parameters.imageOverride }}
    - msbuild

  variables:
    - template: ../../../libraries/ci-build-variables.yml

  steps:
  - ${{ if ne(parameters.prebuildSteps, '') }}:
    - ${{ parameters.prebuildSteps }} # extra steps to run before the build like downloading sni and the required configuration

  - task: MSBuild@1
    displayName: 'Restore nugets'
    inputs:
      solution: build.proj
      msbuildArchitecture: x64
      msbuildArguments: '-t:restore'

  - task: MSBuild@1
    displayName: 'Build Driver'
    inputs:
      solution: build.proj
      msbuildArchitecture: x64
      platform: '$(Platform)'
      configuration: '$(Configuration)'
      msbuildArguments: '-t:BuildAllConfigurations -p:GenerateNuGet=false -p:BuildNumber=$(BuildNumber)'
      clean: true

  - task: MSBuild@1
    displayName: 'Build AKV Provider NetFx'
    inputs:
      solution: build.proj
      msbuildArchitecture: x64
      platform: '$(Platform)'
      configuration: '$(Configuration)'
      msbuildArguments: '-t:BuildAKVNetFx -p:BuildNumber=$(BuildNumber)'

  - task: MSBuild@1
    displayName: 'Build AKV Provider NetCore All OS'
    inputs:
      solution: build.proj
      msbuildArchitecture: x64
      platform: '$(Platform)'
      configuration: '$(Configuration)'
      msbuildArguments: '-t:BuildAKVNetCoreAllOS -p:BuildNumber=$(BuildNumber)'

  - template: ../steps/generate-nuget-package-step.yml@self
    parameters:
      NugetPackageVersion: $(NugetPackageVersion)
      configuration: $(Configuration)
      nuspecPath: 'tools/specs/Microsoft.Data.SqlClient.nuspec'
      OutputDirectory: $(packagePath)
      generateSymbolsPackage: false
      displayName: 'Generate NuGet package M.D.SqlClient'

  - template: ../steps/generate-nuget-package-step.yml@self
    parameters:
      NugetPackageVersion: $(NugetPackageVersion)
      configuration: $(Configuration)
      nuspecPath: 'tools/specs/add-ons/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.nuspec'
      OutputDirectory: $(packagePath)
      generateSymbolsPackage: false
      installNuget: false
      displayName: 'Generate NuGet package AKV Provider'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Artifacts'
    inputs:
      PathtoPublish: $(packagePath)
      ArtifactName: ${{ parameters.artifactName }}
