#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: debug
    type: boolean
    default: false

  - name: poolName
    type: string
    default: ADO-1ES-Pool

  - name: imageOverride
    type: string
    default: ADO-MMS22-SQL19

  - name: jobDisplayName
    type: string

  - name: configProperties
    type: object
    default: {} # - key: 'value'

  - name: prebuildSteps
    type: stepList
    default: []

  - name: artifactName
    type: string
    default: Artifacts

jobs:
- job: ${{ format('{0}', coalesce(parameters.jobDisplayName, parameters.imageOverride, 'unknown_image')) }}

  pool: 
    vmImage: ${{ parameters.imageOverride }} # <<<<< temporary for testing >>>>>
    # name: ${{parameters.poolName }}
    # demands:
    # - imageOverride -equals ${{ parameters.imageOverride }}

  steps:
    - ${{ if ne(parameters.prebuildSteps, '') }}:
      - ${{ parameters.prebuildSteps }} # extra steps to run before the build like downloading sni and the required configuration

    - pwsh: |
        Write-Host "propertyName: ${{ parameters.configProperties.propertyName}}"
        Write-Host "configProperties: ${{ parameters.configProperties }}"
        Write-Host "configProperties['TCPConnectionString']: ${{ parameters.configProperties['TCPConnectionString'] }}"
        Write-Host "configProperties['NPConnectionString']: ${{ parameters.configProperties['NPConnectionString'] }}"
        Write-Host "configProperties['AADAuthorityURL']: ${{ parameters.configProperties['AADAuthorityURL'] }}"
        Write-Host "configProperties['AADClientId']: ${{ parameters.configProperties['AADClientId'] }}"
        Write-Host "configProperties['AADClientSecret']: ${{ parameters.configProperties['AADClientSecret'] }}"
        Write-Host "configProperties['AADTenantId']: ${{ parameters.configProperties['AADTenantId'] }}"
      displayName: 'Print configProperties'

    - ${{ if ne(parameters.configProperties, '{}') }}:
      - template: ../steps/update-config-file-step.yml
        parameters:
          debug: ${{ parameters.debug }}
          ${{ if eq(parameters.configProperties.propertyName, 'TCPConnectionString') }}:
            TCPConnectionString: ${{ parameters.configProperties['TCPConnectionString'].value }}
          ${{ if ne(parameters.configProperties['NPConnectionString'], '') }}:
            NPConnectionString: ${{ parameters.configProperties['NPConnectionString'].value }}
          ${{ if ne(parameters.configProperties['AADAuthorityURL'], '') }}:
            AADAuthorityURL: ${{ parameters.configProperties['AADAuthorityURL'].value }}
          ${{ if ne(parameters.configProperties['AADClientId'], '') }}:
            AADClientId: ${{ parameters.configProperties['AADClientId'].value }}
          ${{ if ne(parameters.configProperties['AADClientSecret'], '') }}:
            AADClientSecret: ${{ parameters.configProperties['AADClientSecret'].value }}
          ${{ if ne(parameters.configProperties['AADTenantId'], '') }}:
            AADTenantId: ${{ parameters.configProperties['AADTenantId'].value }}
