#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: debug
    type: boolean
    default: false

  - name: poolName
    type: string
    default: ADO-1ES-Pool

  - name: imageOverride
    type: string
    default: ADO-MMS22-SQL19

  - name: jobDisplayName
    type: string

  - name: usemanagedSNI
    type: boolean
    default: false

  - name: configProperties
    type: object
    default: {} # - key: 'value'

  - name: prebuildSteps
    type: stepList
    default: []

  - name: artifactName
    type: string
    default: Artifacts

jobs:
- job: ${{ format('{0}', coalesce(parameters.jobDisplayName, parameters.imageOverride, 'unknown_image')) }}

  pool: 
    vmImage: ${{ parameters.imageOverride }} # <<<<< temporary for testing >>>>>
    # name: ${{parameters.poolName }}
    # demands:
    # - imageOverride -equals ${{ parameters.imageOverride }}

  steps:
  - ${{ if ne(parameters.prebuildSteps, '') }}:
    - ${{ parameters.prebuildSteps }} # extra steps to run before the build like downloading sni and the required configuration

  - ${{ if ne(parameters.configProperties, '{}') }}:
    - template: ../steps/update-config-file-step.yml
      parameters:
        debug: ${{ parameters.debug }}
        ${{ if parameters.configProperties.TCPConnectionString }}:
          TCPConnectionString: ${{ parameters.configProperties.TCPConnectionString }}
        ${{ if parameters.configProperties.NPConnectionString }}:
          NPConnectionString: ${{ parameters.configProperties.NPConnectionString }}
        ${{ if parameters.configProperties.AADAuthorityURL }}:
          AADAuthorityURL: ${{ parameters.configProperties.AADAuthorityURL }}
        ${{ if parameters.configProperties.TCPConnectionStringHGSVBS }}:
          TCPConnectionStringHGSVBS: ${{ parameters.configProperties.TCPConnectionStringHGSVBS }}
        ${{ if parameters.configProperties.TCPConnectionStringNoneVBS }}:
          TCPConnectionStringNoneVBS: ${{ parameters.configProperties.TCPConnectionStringNoneVBS }}
        ${{ if parameters.configProperties.TCPConnectionStringAASSGX }}:
          TCPConnectionStringAASSGX: ${{ parameters.configProperties.TCPConnectionStringAASSGX }}
        ${{ if parameters.configProperties.EnclaveEnabled }}:
          EnclaveEnabled: ${{ eq(parameters.configProperties.EnclaveEnabled, 'true') }}
        ${{ if parameters.configProperties.TracingEnabled }}:
          TracingEnabled: ${{ eq(parameters.configProperties.TracingEnabled, 'true') }}
        ${{ if parameters.configProperties.AADPasswordConnectionString }}:
          AADPasswordConnectionString: ${{ parameters.configProperties.AADPasswordConnectionString }}
        ${{ if parameters.configProperties.AADServicePrincipalId }}:
          AADServicePrincipalId: ${{ parameters.configProperties.AADServicePrincipalId }}
        ${{ if parameters.configProperties.AADServicePrincipalSecret }}:
          AADServicePrincipalSecret: ${{ parameters.configProperties.AADServicePrincipalSecret }}
        ${{ if parameters.configProperties.AzureKeyVaultUrl }}:
          AzureKeyVaultUrl: ${{ parameters.configProperties.AzureKeyVaultUrl }}
        ${{ if parameters.configProperties.AzureKeyVaultTenantId }}:
          AzureKeyVaultTenantId: ${{ parameters.configProperties.AzureKeyVaultTenantId }}
        ${{ if parameters.configProperties.UseManagedSNIOnWindows }}:
          UseManagedSNIOnWindows: ${{ parameters.usemanagedSNI }}
        ${{ if parameters.configProperties.UserManagedIdentityClientId }}:
          UserManagedIdentityClientId: ${{ parameters.configProperties.UserManagedIdentityClientId }}
        ${{ if parameters.configProperties.FileStreamDirectory }}:
          FileStreamDirectory: ${{ parameters.configProperties.FileStreamDirectory }}
        ${{ if parameters.configProperties.LocalDbAppName }}:
          LocalDbAppName: ${{ parameters.configProperties.LocalDbAppName }}
        ${{ if parameters.configProperties.LocalDbSharedInstanceName }}:
          LocalDbSharedInstanceName: ${{ parameters.configProperties.LocalDbSharedInstanceName }}
        ${{ if parameters.configProperties.AliasName }}:
          AliasName: ${{ parameters.configProperties.AliasName }}
        ${{ if parameters.configProperties.SupportsIntegratedSecurity }}:
          SupportsIntegratedSecurity: ${{ eq(parameters.configProperties.SupportsIntegratedSecurity, 'true') }}
        ${{ if parameters.configProperties.SupportsFileStream }}:
          SupportsFileStream: ${{ eq(parameters.configProperties.SupportsFileStream, 'true') }}
        ${{ if parameters.configProperties.DNSCachingConnString }}:
          DNSCachingConnString: ${{ parameters.configProperties.DNSCachingConnString }}
        ${{ if parameters.configProperties.DNSCachingServerCR }}:
          DNSCachingServerCR: ${{ parameters.configProperties.DNSCachingServerCR }}
        ${{ if parameters.configProperties.DNSCachingServerTR }}:
          DNSCachingServerTR: ${{ parameters.configProperties.DNSCachingServerTR }}
        ${{ if parameters.configProperties.EnclaveAzureDatabaseConnString }}:
          EnclaveAzureDatabaseConnString: ${{ parameters.configProperties.EnclaveAzureDatabaseConnString }}
        ${{ if parameters.configProperties.IsDNSCachingSupportedCR }}:
          IsDNSCachingSupportedCR: ${{ eq(parameters.configProperties.IsDNSCachingSupportedCR, 'true') }}
        ${{ if parameters.configProperties.IsDNSCachingSupportedTR }}:
          IsDNSCachingSupportedTR: ${{ eq(parameters.configProperties.IsDNSCachingSupportedTR, 'true') }}
        ${{ if parameters.configProperties.IsAzureSynapse }}:
          IsAzureSynapse: ${{ eq(parameters.configProperties.IsAzureSynapse, 'true') }}
        ${{ if parameters.configProperties.ManagedIdentitySupported }}:
          ManagedIdentitySupported: ${{ eq(parameters.configProperties.ManagedIdentitySupported, 'true') }}

    - pwsh: |
        New-Item -Path ${{ parameters.configProperties.FileStreamDirectory }} -ItemType Directory
      displayName: 'Create FileStreamFolder'
      retryCountOnTaskFailure: 2
      continueOnError: true
