#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: poolName
    type: string
    default: ADO-1ES-Pool

  - name: imageOverride
    type: string
    default: ADO-MMS22-SQL19

  - name: jobDisplayName
    type: string

  - name: configProperties
    type: object
    default: {} # - key: 'value'

  - name: prebuildSteps
    type: stepList
    default: []

  - name: artifactName
    type: string
    default: Artifacts

jobs:
- job: ${{ format('{0}', coalesce(parameters.jobDisplayName, parameters.imageOverride, 'unknown_image')) }}

  pool: 
    vmImage: ${{ parameters.imageOverride }} # <<<<< temporary for testing >>>>>
    # name: ${{parameters.poolName }}
    # demands:
    # - imageOverride -equals ${{ parameters.imageOverride }}

  steps:
    - ${{ if ne(parameters.prebuildSteps, '') }}:
      - ${{ parameters.prebuildSteps }} # extra steps to run before the build like downloading sni and the required configuration

    - ${{ if ne(parameters.configProperties, '{}') }}:
      - template: ../steps/update-config-file-step.yml
        parameters:
          ${{ each param in parameters.configProperties }}:
            ${{ if eq(param.key, 'TCPConnectionString') }}:
              TCPConnectionString: ${{ param.value }}
            ${{ elseif eq(param.key, 'NPConnectionString') }}:
              NPConnectionString: ${{ param.value }}
            ${{ elseif eq(param.key, 'TracingEnabled') }}:
              TracingEnabled: ${{ param.value }}
