#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(DayOfYear)$(Rev:rr)
trigger: none
  # branches:
  #   include:
  #   - internal/main
  # paths:
  #   include:
  #   - src
  #   - eng
  #   - tools
  #   - .config
  #   - build.proj
  #   - Nuget.config
  #   - '*.cmd'
  #   - '*.sh'

# schedules:
# - cron: '30 4 * * Mon'
#   displayName: Weekly Sunday 9:30 PM (UTC - 7) Build
#   branches:
#     include:
#     - internal/main
#   always: true

# - cron: '30 3 * * Mon-Fri'
#   displayName: Mon-Fri 8:30 PM (UTC - 7) Build
#   branches:
#     include:
#     - internal/main

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  - template: libraries/ci-build-variables.yml

  - name: artifactName
    value: Artifacts

  - name: defaultPoolName
    value: ADO-1ES-Pool

stages:
  # - stage: build
  #   displayName: 'Build NuGet Packages'
  #   jobs:
  #   - template: common/templates/jobs/ci-build-nugets-job.yml
  #     parameters:
  #       artifactName: $(artifactName)

  - template: common/templates/stages/ci-run-tests-stage.yml
    parameters:
      # dependsOn: 'build'
      debug: ${{ parameters.debug }}

      testConfigurations:
        windows_sql_19: # configuration name
          pool: $(defaultPoolName) # pool name
          images: # list of images to run tests on
            Windows22_Sql19: ADO-MMS22-SQL19 # image display name: image name from the pool
          TargetFrameworks: [net462, net6.0] #[net462, net6.0, net8.0] # list of target frameworks to run
          buildPlatforms: [AnyCPU]
          testSets: [1] # [1, 2, 3] # list of test sets to run
          useManagedSNIOnWindows: [false, true] # can be used for .NET Core only tests on Windows: [false, true], [false] or [true] values are allowed
          configProperties:
            # config.json properties
            TCPConnectionString: $(SQL_TCP_CONN_STRING)
            NPConnectionString: $(SQL_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            FileStreamDirectory: $(FileStreamDirectory)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
            AliasName: $(SQLAliasName)
            # extra config properties
            SQLRootPath: $(SQL19RootPath)
            enableLocalDB: true
            x86TestTargetFrameworks: [net6.0] # target frameworks should run tests on x86 as well

      prebuildSteps:
      - script: SET
        displayName: 'Print Environment Variables'
      # - task: DownloadPipelineArtifact@2
      #   displayName: 'Download NuGet Package'
      #   inputs:
      #     buildType: current
      #     artifact: $(artifactName)
      #     patterns: '**/*.nupkg'
      #     targetPath: $(Pipeline.Workspace)/$(artifactName)
      - task: DownloadPipelineArtifact@2
        displayName: 'Download NuGet Package'
        inputs:
          buildType: specific
          project: 'ADO.Net'
          definition: 1831 # test-Davoud, #1825: self 
          artifact: $(artifactName)
          patterns: '**/*.nupkg'
          targetPath: $(Pipeline.Workspace)/$(artifactName)
      - template: common/templates/steps/update-nuget-config-local-feed-step.yml
        parameters:
          downloadedNugetPath: $(Pipeline.Workspace)\$(artifactName)
          debug: ${{ parameters.debug }}
