#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(DayOfYear)$(Rev:rr)
trigger: none
  # batch: true
  # branches:
  #   include:
  #   - internal/main
  # paths:
  #   include:
  #   - src
  #   - eng
  #   - tools
  #   - .config
  #   - build.proj
  #   - Nuget.config
  #   - '*.cmd'
  #   - '*.sh'

# schedules:
# - cron: '30 4 * * Mon'
#   displayName: Weekly Sunday 9:30 PM (UTC - 7) Build
#   branches:
#     include:
#     - internal/main
#   always: true

# - cron: '30 3 * * Mon-Fri'
#   displayName: Mon-Fri 8:30 PM (UTC - 7) Build
#   branches:
#     include:
#     - internal/main

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

- name: targetFrameworks
  displayName: 'Target Frameworks on Windows'
  type: object
  default: [net462, net6.0, net8.0]

- name: targetFrameworksLinux
  displayName: 'Target Frameworks on Linux'
  type: object
  default: [net6.0, net8.0]

- name: buildPlatforms
  displayName: 'Build Platforms'
  type: object
  default: [AnyCPU]

- name: testSets
  displayName: 'Test Sets'
  type: object
  default: [1, 2, 3]

- name: useManagedSNI
  displayName: 'Use Managed/Native SNI  ([false, true], [false] or [true] values are allowed)'
  type: object
  default: [false, true]

- name: publishTestResults
  displayName: 'Publish Test Results'
  type: boolean
  default: true

variables:
  - template: libraries/ci-build-variables.yml

  - name: artifactName
    value: Artifacts

  - name: defaultPoolName
    value: ADO-1ES-Pool

stages:
  # - stage: build
  #   displayName: 'Build NuGet Packages'
  #   jobs:
  #   - template: common/templates/jobs/ci-build-nugets-job.yml
  #     parameters:
  #       artifactName: $(artifactName)

  - template: common/templates/stages/ci-run-tests-stage.yml
    parameters:
      # dependsOn: 'build'
      debug: ${{ parameters.debug }}

      # steps to run prior to building and running tests
      prebuildSteps:
      # - template: common/templates/steps/ci-prebuild-step.yml
      #   parameters:
      #     debug: ${{ parameters.debug }}
      #     artifactName: $(artifactName)

      # temporary steps
      - script: SET
        displayName: 'Print Environment Variables'
      # - task: DownloadPipelineArtifact@2
      #   displayName: 'Download NuGet Package'
      #   inputs:
      #     buildType: current
      #     artifact: $(artifactName)
      #     patterns: '**/*.nupkg'
      #     targetPath: $(Pipeline.Workspace)/$(artifactName)
      - task: DownloadPipelineArtifact@2
        displayName: 'Download NuGet Package'
        inputs:
          buildType: specific
          project: 'ADO.Net'
          definition: 1831 # test-Davoud, #1825: self 
          artifact: $(artifactName)
          patterns: '**/*.nupkg'
          targetPath: $(Pipeline.Workspace)/$(artifactName)
      
      - template: common/templates/steps/update-nuget-config-local-feed-step.yml
        parameters:
          downloadedNugetPath: $(Pipeline.Workspace)\$(artifactName)
          debug: ${{ parameters.debug }}

# test stages configurations
  # self hosted SQL Server on Windows
      testConfigurations:
        windows_sql_19: # configuration name
          pool: $(defaultPoolName) # pool name
          images: # list of images to run tests on
            Win22_Sql19: ADO-MMS22-SQL19 # stage display name: image name from the pool
          TargetFrameworks: ${{parameters.targetFrameworks }} #[net462, net6.0, net8.0] # list of target frameworks to run
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }} # [1, 2, 3] # list of test sets to run
          useManagedSNI: ${{parameters.useManagedSNI }} # can be used for .NET Core only tests on Windows: [false, true], [false] or [true] values are allowed
          publishTestResults: ${{parameters.publishTestResults }} # publish test results to pipeline
          configSqlFor: local # setup Sql Server (local | azure | enclave)
          configProperties:
            # config.json properties
            TCPConnectionString: $(SQL_TCP_CONN_STRING)
            NPConnectionString: $(SQL_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            FileStreamDirectory: $(FileStreamDirectory)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
            AliasName: $(SQLAliasName)
            # extra config properties
            x86TestTargetFrameworks: [net6.0] # target frameworks should run tests on x86 as well
            SQLRootPath: $(SQL19RootPath)
            enableLocalDB: true
            # instanceName: default: MSSQLSERVER
            # user: default: $(user)
            # saUser: default: $(saUser)
            # password: default: $(password)
            # fileStreamDirectory: default: ''
            # x64AliasRegistryPath: default: $(x64AliasRegistryPath)
            # x86AliasRegistryPath: default: $(x86AliasRegistryPath)
            # SQLAliasName: default: $(SQLAliasName)
            # SQLAliasPort: default: $(SQLAliasPort)
            # targetNetCoreVersion: default: $(MainTargetNetCoreVersion)
            # databaseName: default: Northwind
            # localDbAppName: default: $(LocalDbAppName)
            # localDbSharedInstanceName: default: $(LocalDbSharedInstanceName)
            # skipSqlConfiguration: # skips the SQL configuration step

        windows_sql_22: 
          pool: $(defaultPoolName)
          images:
            Win22_Sql22: ADO-MMS22-SQL22 
          TargetFrameworks: ${{parameters.targetFrameworks }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          publishTestResults: ${{parameters.publishTestResults }}
          configSqlFor: local
          configProperties:
            # config.json properties
            TCPConnectionString: $(SQL_TCP_CONN_STRING)
            NPConnectionString: $(SQL_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            FileStreamDirectory: $(FileStreamDirectory)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
            AliasName: $(SQLAliasName)
            # extra config properties
            x86TestTargetFrameworks: [net462] # target frameworks should run tests on x86 as well
            SQLRootPath: $(SQL22RootPath)
            enableLocalDB: true

        windows_sql_22_named_instance:
          pool: $(defaultPoolName)
          images:
            Win22_Sql22_named_instance: ADO-MMS22-SQL22-WITH-NAMED-INSTANCE
          TargetFrameworks: ${{parameters.targetFrameworks }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          publishTestResults: ${{parameters.publishTestResults }}
          configSqlFor: local
          configProperties:
            # config.json properties
            TCPConnectionString: $(SQL_TCP_INSTANCE_CONN_STRING)
            NPConnectionString: $(SQL_NP_INSTANCE_CONN_STRING)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            # extra config properties
            SQLRootPath: $(SQL22RootPath)
            instanceName: $(NamedInstance)

    # Azure SQL Server Windows
        windows_azure_sql:
          pool: $(defaultPoolName) 
          images: 
            Win22_Azure_Sql: ADO-MMS22-SQL19
            win11_Azure_Sql: ADO-CI-Win11
          TargetFrameworks: ${{parameters.targetFrameworks }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          publishTestResults: ${{parameters.publishTestResults }}
          configSqlFor: azure
          configProperties:
            # config.json properties
            TCPConnectionString: $(AZURE_DB_TCP_CONN_STRING)
            NPConnectionString: $(AZURE_DB_NP_CONN_STRING)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

        windows_azure_arm64_sql:
          pool: ADO-CI-PUBLIC-ARM64-1ES-EUS2-POOL
          images: 
            Win22_Azure_ARM64_Sql: ADO-WIN11-ARM64
          TargetFrameworks: ${{parameters.targetFrameworks }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: ${{parameters.useManagedSNI }}
          publishTestResults: ${{parameters.publishTestResults }}
          configSqlFor: azure
          configProperties:
            # config.json properties
            TCPConnectionString: $(AZURE_DB_TCP_CONN_STRING_eastus)
            NPConnectionString: $(AZURE_DB_NP_CONN_STRING_eastus)
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR_eastus)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId_eastus)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

        windows_enclave_sql:
          pool: ADO-CI-AE-1ES-Pool
          images: 
            Win22_Enclave_Sql19: ADO-MMS22-SQL19
          TargetFrameworks: ${{parameters.targetFrameworks }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: [AE]
          useManagedSNI: ${{parameters.useManagedSNI }}
          publishTestResults: ${{parameters.publishTestResults }}
          configSqlFor: enclave
          configProperties:
            # config.json properties
            TCPConnectionString: ''
            NPConnectionString: ''
            TCPConnectionStringHGSVBS: $(SQL_TCP_CONN_STRING_HGSVBS)
            TCPConnectionStringNoneVBS: $(SQL_TCP_CONN_STRING_NoneVBS)
            TCPConnectionStringAASSGX: $(SQL_TCP_CONN_STRING_AASSGX)
            EnclaveEnabled: true
            AADAuthorityURL: $(AADAuthorityURL)
            AADPasswordConnectionString: $(AAD_PASSWORD_CONN_STR)
            AADServicePrincipalId: $(AADServicePrincipalId)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: $(SupportsIntegratedSecurity)
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            AliasName: $(SQLAliasName)            
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)

    # self hosted SQL Server on Linux
        linux_sql_19_22:
          pool: $(defaultPoolName)
          images:
            Ubuntu20_Sql19: ADO-UB20-Sql19
            Ubuntu20_Sql22: ADO-UB2004-SQL2022
          TargetFrameworks: ${{parameters.targetFrameworksLinux }}
          buildPlatforms: ${{parameters.buildPlatforms }}
          testSets: ${{parameters.testSets }}
          useManagedSNI: [true]
          publishTestResults: ${{parameters.publishTestResults }}
          configSqlFor: local
          configProperties:
            # config.json properties
            TCPConnectionString: $(SQL_TCP_CONN_STRING)
            NPConnectionString: $(SQL_NP_CONN_STRING)
            AADServicePrincipalSecret: $(AADServicePrincipalSecret)
            AzureKeyVaultUrl: $(AzureKeyVaultUrl)
            AzureKeyVaultTenantId: $(AzureKeyVaultTenantId)
            SupportsIntegratedSecurity: false
            UserManagedIdentityClientId: $(UserManagedIdentityClientId)
            LocalDbAppName: $(LocalDbAppName)
            LocalDbSharedInstanceName: $(LocalDbSharedInstanceName)
            AliasName: $(SQLAliasName)

    # Azure Sql Server Linux
    # Azure Sql Server Mac
