#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################

name: $(Year:YY)$(DayOfYear)$(Rev:.rr)


parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

- name: configProperties
  type: object
  default:
    TCPConnectionString: $(SQL_TCP_CONN_STRING)
    NPConnectionString: $(SQL_NP_CONN_STRING)
    AADAuthorityURL: $(AADAuthorityURL)

- name: testArray
  type: object
  default: [1, 2, 3]

- name: testCfgs
  type: object
  default:
    - windows-sql:
        pool: ADO-1ES-Pool
        versions:
          Windows2019:
            image: ADO-MMS22-SQL19
            name: Windows2019
            sqlServer: SQL19
          Windows2022:
            image: ADO-MMS22-SQL22
            name: Windows2022
            sqlServer: SQL22
        TargetFrameworks: [net462, net6.0, net8.0]
        TFwithManagedSNI: [net6.0, net8.0]
        buildPlatforms: [AnyCPU]
        testPlatforms: [AnyCPU, x86]
        testSets: [1, 2, 3]
        connectionStrings:
          TCPConnectionString: $(SQL_TCP_CONN_STRING)
          NPConnectionString: $(SQL_NP_CONN_STRING)
          AADAuthorityURL: $(AADAuthorityURL)

variables:
  # - template: libraries/ci-configuration-variables.yml
  - name: artifactName
    value: Artifacts

stages:
- stage: test1
  jobs:

  - job: job1
    pool: 
      vmImage: 'windows-latest'

    steps:
    - script: SET
      displayName: 'Print Environment Variables'

# -------------Config--------------------------------------------------------------
    - ${{ each cfg in parameters.testCfgs }}:
      - script: | 
          echo '${{ cfg.key }}'
          echo '${{ cfg.value.pool }}'
        displayName: 'Print testCfgs items ${{ cfg.key }}'
# -------------Version--------------------------------------------------------------
      - ${{ each version in cfg.value.versions }}:
        - ${{ each osCfg in version.value }}:
          - script: |
              echo 'image: ${{ osCfg.image }}'
              echo 'name: ${{ osCfg.name }}'
              echo 'sqlServer: ${{ osCfg.sqlServer }}'
            displayName: 'Print versions items ${{ version.key }}'
# --------------TF-------------------------------------------------------------
      - ${{ each item in cfg.value.TargetFrameworks }}:
        - script: echo '${{ item }}'
          displayName: 'Print TargetFrameworks items ${{ item }}'
# --------------Cnn String------------------------------------------------------------
      - ${{ each item in cfg.value.connectionStrings }}:
        - script: echo '${{ item.value }}'
          displayName: 'Print connectionStrings items ${{ item.key }}'
# ---------------------------------------------------------------------------
    
    - ${{ each item in parameters.testArray }}:
      - script: echo '${{ item }}'
        displayName: 'Print testArray items ${{ item }}'
    
    - ${{ each pair in parameters.configProperties }}:
      - script: echo '${{ pair.value }}'
        displayName: 'Print Config Properties ${{ pair.key }}'
