#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: debug
    type: boolean
    default: false

  - name: testConfigurations
    type: object

  - name: dependsOn
    type: string
    default: ''

  - name: prebuildSteps
    type: stepList
    default: []

stages:
  - ${{ each config in parameters.testConfigurations }}:
    - ${{ each image in config.value.images }}:
      - stage: ${{ image.key }}
        ${{ if ne(parameters.dependsOn, '') }}:
          dependsOn: ${{ parameters.dependsOn }}
        ${{ else }}:
          dependsOn: []
        jobs:
          # - ${{ if eq(config.type, 'Windows') }}:
        - ${{ each targetFramework in config.value.TargetFrameworks }}:
          - ${{ each platform in config.value.buildPlatforms }}:
            - ${{ each testSet in config.value.TestSets }}:
              - ${{ each useManagedSNI in config.value.useManagedSNIOnWindows }}:
                - template: ../jobs/ci-run-tests-job.yml
                  parameters:
                    debug: ${{ parameters.debug }}
                    poolName: ${{ config.value.pool }}
                    imageOverride: ${{ image.value }}
                    jobDisplayName: ${{ format('{0}_{1}_{2}_{3}', replace(targetFramework, '.', '_'), platform, usemanagedSNI, testSet) }}
                    configProperties: ${{ config.value.configProperties }}
                    useManagedSNI: ${{ useManagedSNI }}
                    prebuildSteps: ${{ parameters.prebuildSteps }}
